# Generated by Django 3.0.2 on 2020-02-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoo',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
