# Specifying which user to be used on server
user ubuntu;
# Number of worker processes to handle incoming requests
worker_processes 1;

events {
    # Max connections a worker process can handle at a time
    worker_connections 1024;
}


http {
    include mime.types;
    default_type application/octet-stream;
  
	# Creating a new variable "$time_format" from the built-in variables
	# $time_iso8601 and $msec, so we can use it in log files
    map "$time_iso8601:$msec" $time_format {
        ~^(\d+-\d+-\d+)T(\d+:\d+:\d+)\+\d+:\d+:\d+\.(\d+)$ "$1 $2.$3";
    }

	# Logs format and file config. Also, for this we can't use the variables to
	# define file path
    log_format pg_logs_format '$time_format $host{Nginx} : $request_method $uri $status';
    access_log /home/ubuntu/Django/SampleProject/logs/logs.log pg_logs_format;
    error_log /home/ubuntu/Django/SampleProject/logs/logs.log;
    #access_log P:/Django/SampleProject/logs/logs.log logs_format;
    #error_log P:/Django/SampleProject/logs/logs.log;

    # Telling Nginx to use the OS's sendfile() system call for optimized transmission
    # of the static files
    sendfile on;

    # Creating variable $project_path and setting value based on variable $host
    map $host $project_path {
        default /home/ubuntu/Django/SampleProject;
        localhost P:/Nginx/PrateekGupta;
    }

    server {
        # Listening for requests on port 80
        listen 80;

		# Filtering for domains
        server_name *.prateek-gupta.com prateek-gupta.com ;

        # Redirecting requests for Django Sample Project to port 8000
		location "/sample_project" {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
        }
    }
}

